#!/bin/sh

# PROVIDE: transvpnmon
# REQUIRE: transmission
# REQUIRE: openvpn
# REQUIRE: 3proxy

. /etc/rc.subr

name=transvpnmon
load_rc_config $name

#start_cmd="${name}_start"

rcvar="${name}_enable"
pidfile="/var/run/${name}.pid"

command="/usr/sbin/daemon"
command_args="-c -f -P ${pidfile} /root/transvpnmon/transvpnmon.py"
#command="/usr/sbin/transvpnmon.py"
#command_interpreter=/usr/local/bin/python3
#start_cmd="/usr/sbin/daemon -p $pidfile $command"

run_rc_command "$1"
